### ISSUE TITLE
Method Illuminate\Routing\RouteRegistrar::withoutMiddleware does not exist

### ISSUE THREAD

**Issue by andreifiroiu** [moharrum/laravel-adminer#2]
Out of nowhere, when I just ran a "composer update", started to get this:

>php artisan

   BadMethodCallException 

  Method Illuminate\Routing\RouteRegistrar::withoutMiddleware does not exist.

  at vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php:222
    218▕ 
    219▕             return $this->attribute($method, $parameters[0]);
    220▕         }
    221▕ 
  ➜ 222▕         throw new BadMethodCallException(sprintf(
    223▕             'Method %s::%s does not exist.', static::class, $method
    224▕         ));
    225▕     }
    226▕ }

  • Bad Method Call: Did you mean Illuminate\Routing\RouteRegistrar::registerRoute() ? 

      +10 vendor frames 
  11  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Moharrum\LaravelAdminer\Providers\LaravelAdminerServiceProvider))

      +5 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

========================================================================================================================================================================================

The entire stack trace:

[2020-11-16 13:29:30] local.ERROR: Method Illuminate\Routing\RouteRegistrar::withoutMiddleware does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Routing\\RouteRegistrar::withoutMiddleware does not exist. at /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php:222)
[stacktrace]
#0 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/moharrum/laravel-adminer/src/Providers/LaravelAdminerServiceProvider.php(78): Illuminate\\Routing\\RouteRegistrar->__call('withoutMiddlewa...', Array)
#1 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/moharrum/laravel-adminer/src/Providers/LaravelAdminerServiceProvider.php(61): Moharrum\\LaravelAdminer\\Providers\\LaravelAdminerServiceProvider->bindManagerRoutes()
#2 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/moharrum/laravel-adminer/src/Providers/LaravelAdminerServiceProvider.php(38): Moharrum\\LaravelAdminer\\Providers\\LaravelAdminerServiceProvider->bindRoutesAutomatically()
#3 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Moharrum\\LaravelAdminer\\Providers\\LaravelAdminerServiceProvider->boot()
#4 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(869): Illuminate\\Container\\Container->call(Array)
#9 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Moharrum\\LaravelAdminer\\Providers\\LaravelAdminerServiceProvider))
#10 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Moharrum\\LaravelAdminer\\Providers\\LaravelAdminerServiceProvider), 36)
#11 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#12 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#13 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#14 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#15 /Users/andreifiroiu/Dev/ValetSites/eshop/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#16 /Users/andreifiroiu/Dev/ValetSites/eshop/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"} 

================================================================================================================================================================================

My composer.json:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3.0",
        "ext-curl": "*",
        "ext-gd": "*",
        "ext-json": "*",
        "ext-soap": "*",
        "arcanedev/log-viewer": "^8.0",
        "buglinjo/laravel-webp": "^2.0",
        "dialect/laravel-gdpr-compliance": "^1.4",
        "doctrine/dbal": "~2.3",
        "dymantic/laravel-instagram-feed": "^2.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "imtigger/laravel-job-status": "^1.2",
        "infyomlabs/coreui-templates": "8.0.x-dev",
        "infyomlabs/laravel-generator": "8.0.x-dev",
        "intervention/image": "^2.5",
        "intervention/imagecache": "^2.4",
        "jenssegers/agent": "^2.6",
        "laravel/framework": "^8.0",
        "laravel/legacy-factories": "^1.1",
        "laravel/socialite": "^5.0",
        "laravel/telescope": "^4.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "laravelcollective/html": "^6.2",
        "livewire/livewire": "^1.2",
        "maatwebsite/excel": "^3.1",
        "paquettg/php-html-parser": "^3.0",
        "pgrimaud/instagram-user-feed": "^6.3",
        "sentry/sentry-laravel": "^2.2",
        "solarium/solarium": "^6.0",
        "spatie/laravel-cookie-consent": "^2.12",
        "spatie/laravel-newsletter": "^4.8",
        "spatie/laravel-schedule-monitor": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.3",
        "barryvdh/laravel-ide-helper": "^2.7",
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "laravel/dusk": "^6.4",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.0",
        "spatie/laravel-web-tinker": "^1.7"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "files": [
            "app/helpers.php"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by kmuharam** [comment]
Hi @andreifiroiu,
sorry about that, I decided to use `withoutMiddleware()` on registered routes, as far as I know since 7.7.0 and up this method should exists, I have tested changes on Laravel 7 and assumed Laravel 8 will work fine, but I guess not.

I have reverted the changes in `1.3.3`, just do another update and everything will be fine.
